// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfivvdpnhnascpcwncau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmaXZ2ZHBuaG5hc2NwY3duY2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTM0NTEsImV4cCI6MjA1NTM4OTQ1MX0.5Yw2Vgb0QLv6a1PcCDrWK4zxsP1OXX_gy5cUZq8zp6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);