// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpzhkqsfckwpbhxplhee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwemhrcXNmY2t3cGJoeHBsaGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDgxODcsImV4cCI6MjA1OTg4NDE4N30.m6ULosHNNjDDBmq5PFHI4jTL1NefkSjfZrrC-DTAoyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);